### PR TITLE
added online_multiplayer to playerAmount

### PR DESCRIPTION
**Pull request by albertliang**

### CODE REVIEW

**Comment by vmichalak** [comment]
Hi, 
I check this during the day.
Thank you in advance 👍 
Valentin

**Comment by vmichalak** [comment]
Hi,
I can't accept your pull request, a problem occured when i test with: sample/app.js
Can you check that ?
Valentin

```
index.js:22
ar totalPageNb = cheerio.load(html)('.search_pagination_right a')[2].children[
                                                                    ^
TypeError: Cannot read property 'children' of undefined
    at Request._callback (D:\Downloads\steam-store-parser-js-master\steam-store-parser-js-master\lib\index.js:22:72)
    at Request.self.callback (D:\Downloads\steam-store-parser-js-master\steam-store-parser-js-master\node_modules\request\request.js:188:22)

    at Request.emit (events.js:110:17)
    at Request.<anonymous> (D:\Downloads\steam-store-parser-js-master\steam-store-parser-js-master\node_modules\request\request.js:1171:10)
    at Request.emit (events.js:107:17)
    at IncomingMessage.<anonymous> (D:\Downloads\steam-store-parser-js-master\steam-store-parser-js-master\node_modules\request\request.js:1
091:12)
    at IncomingMessage.g (events.js:199:16)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

```

**Comment by albertliang** [comment]
That's because there are no indie/platformer/windows/online_multiplayer games in existence. Try removing 'platformer' and you'll get results back.

**Comment by vmichalak** [comment]
Thank you ! 👍

**Pull request merged**
